import type { ConfigFile } from "./src/config.ts";

export const defaultConfig: ConfigFile = {
  github: {
    ownerType: "user",
    lookbackHours: 24,
    perPage: 100,
    maxPages: 5,
    allowlist: [],
    blocklist: [],
    includePrivate: false,
  },
  output: {
    format: "markdown",
    prefix: "reports",
    validateSchema: false,
  },
  llm: {
    model: "gemini-3-flash-preview",
    promptTemplate:
      "You are a helpful reporter that summarizes GitHub activity.\n\nReturn the response in the requested format. Be concise and factual. Highlight notable changes and themes.\nIf repositories have no commits in the window, do not list them individually; instead report a single line with the count.",
  },
  storage: {
    type: "local",
    bucket: "",
    region: "",
    endpoint: "",
    forcePathStyle: false,
  },
  network: {
    retryCount: 2,
    retryBackoffMs: 500,
  },
  logging: {
    level: "info",
    includeTimings: true,
    format: "pretty",
    color: true,
    timeZone: "Europe/Ljubljana",
    contextMaxBytes: 4000,
  },
  webhook: {},
  context: {
    includeReadme: true,
    includeLlmTxt: true,
    includeRepoDescription: true,
    includeRepoTopics: true,
    includeDiffSummary: true,
    includeDiffSnippets: true,
    includePullRequests: true,
    includePullRequestDetails: false,
    includeIssues: true,
    maxReadmeBytes: 36000,
    maxLlmTxtBytes: 24000,
    maxDiffFilesPerCommit: 60,
    maxDiffCommitsPerRepo: 30,
    maxSnippetCommitsPerRepo: 15,
    maxSnippetFilesPerCommit: 15,
    maxSnippetLinesPerFile: 200,
    maxSnippetBytesPerRepo: 60000,
    maxPullRequestsPerRepo: 60,
    maxIssuesPerRepo: 60,
    ignoreExtensions: [
      ".lock",
      ".min.js",
      ".min.css",
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".svg",
      ".webp",
    ],
  },
};
