import type { ConfigFile } from "./src/config.ts";

export const defaultConfig: ConfigFile = {
  github: {
    owner: "zerodays",
    ownerType: "org",
    perPage: 100,
    maxPages: 5,
    includePrivate: true,
  },
  output: {
    format: "markdown",
    prefix: "reports",
  },
  llm: {
    model: "gemini-3-flash-preview",
  },
  storage: {
    type: "s3",
    bucket: "github-reporter",
    region: "auto",
    endpoint:
      "https://40d3f89c67347f96408cfa1ff6ec4f11.r2.cloudflarestorage.com",
    forcePathStyle: true,
  },
  network: {
    retryCount: 2,
    retryBackoffMs: 500,
  },
  logging: {
    level: "info",
    includeTimings: true,
    format: "pretty",
    color: true,
  },
  timeZone: "Europe/Ljubljana",
  webhook: {},
  context: {
    includeReadme: true,
    includeLlmTxt: true,
    includeRepoDescription: true,
    includeRepoTopics: true,
    includeDiffSummary: true,
    includeDiffSnippets: true,
    includePullRequests: true,
    includePullRequestDetails: true,
    includeIssues: true,
    maxReadmeBytes: 36000,
    maxLlmTxtBytes: 24000,
    maxDiffFilesPerCommit: 60,
    maxDiffCommitsPerRepo: 30,
    maxSnippetCommitsPerRepo: 15,
    maxSnippetFilesPerCommit: 15,
    maxSnippetLinesPerFile: 200,
    maxSnippetBytesPerRepo: 60000,
    maxPullRequestsPerRepo: 60,
    maxIssuesPerRepo: 60,
    ignoreExtensions: [
      ".lock",
      ".min.js",
      ".min.css",
      ".png",
      ".jpg",
      ".jpeg",
      ".gif",
      ".svg",
      ".webp",
    ],
  },
};
